# Idrid regions dataset creation

# general options
path_data: 'data/IDRiD/new_idrid' # contains images and masks, and each contains train, val, test (pp 59 of notebook)
path_result: 'data/IDRiD' # the name of this config file is appended at the end
format_gt: 'tif'

# options for image preparation (preprocessing)
overwrite_img: False # whether or not to overwrite the processed images
resize: True
size: 448
normalize: True # whether or not to normalize RGB channels

# options for qa generation
overwrite_qa: False
num_regions: 100 # number of windows (QA pairs) to be generated for each image
max_window_side: 85 # with respect to <size> parameter of this file (if resize is True)
min_window_side: 50 # with respect to <size> parameter of this file (if resize is True)
proportion_deviation: 0.2 # deviation around one for the windows 
map_class_suffix: {hard exudate: EX} # map from classes for which there is a segmentation to suffixes of mask images
question_templates: {inside: are there <> in this region}

