# Idrid regions dataset creation

# general options
path_data: 'data/pascal/VOC2012' # contains images and masks, and each contains train, val, test (pp 59 of notebook)
path_result: 'data/pascal/VOC2012' # the name of this config file is appended at the end
format_gt: 'tif'

# options for image preparation (preprocessing)
overwrite_img: False # whether or not to overwrite the processed images
resize: True
size: 448
normalize: True # whether or not to normalize RGB channels

# options for qa generation
overwrite_qa: False
num_regions: 10 # number of windows (QA pairs) to be generated for each image
max_window_side: 85 # with respect to <size> parameter of this file (if resize is True)
min_window_side: 50 # with respect to <size> parameter of this file (if resize is True)
proportion_deviation: 0.2 # deviation around one for the windows
threshold: 10
window_offset: 2 # offset for the window in the resized space. It determines a region in the borders where the window cannot be
max_window_size_changes: 12
map_class_suffix: {'aeroplane': 'aeroplane', 'bicycle': 'bicycle', 'bird': 'bird', 'boat': 'boat', 'bottle': 'bottle', 'bus': 'bus', 'car': 'car', 'cat': 'cat', 'chair': 'chair', 'cow': 'cow', 'diningtable': 'diningtable', 'dog': 'dog', 'horse': 'horse', 'motorbike': 'motorbike', 'person': 'person', 'plant': 'plant', 'sheep': 'sheep', 'sofa': 'sofa', 'train': 'train', 'tv': 'tv'}
question_templates: {inside: are there <> in this region}
